# Generated by Django 5.1.7 on 2025-03-30 17:57

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Livre', max_length=10)),
                ('pedido', models.PositiveIntegerField(default=0)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('pessoas_pagaram', models.IntegerField(default=0)),
                ('numero_pessoas', models.IntegerField(default=1)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('not_numerico', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesas', to='empresa.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='ItemMesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('preco_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('produto_nome', models.CharField(max_length=100)),
                ('produto_slug', models.SlugField()),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('produto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.produto')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mesa.mesa')),
            ],
        ),
    ]
